/**
 * Write .env from database settings — keeps message + connect keys in sync.
 */
const fs = require('fs');
const path = require('path');
const { queryAll } = require('../database/db');

const PROJECT_ROOT = path.resolve(__dirname, '../../../');
const ENV_FILE = path.join(PROJECT_ROOT, '.env');

const ENV_KEYS = [
  'LINKEDIN_ACCOUNT_ID',
  'MAX_CONNECTIONS', 'MAX_SCROLL_ATTEMPTS', 'DELAY_BETWEEN_PROFILES_MS',
  'DELAY_BETWEEN_PROFILES_MIN_MS', 'DELAY_BETWEEN_PROFILES_MAX_MS',
  'ACTION_DELAY_MS', 'TYPE_FALLBACK_DELAY_MS', 'PAGE_TIMEOUT_MS',
  'SCROLL_PAUSE_MS', 'SEND_ENABLED', 'HEADLESS', 'BROWSER_PROFILE_DIR',
  'LINKEDIN_CONNECTIONS_URL', 'RESUME_URL',
  'CONNECT_ROLE', 'CONNECT_LOCATION', 'CONNECT_MAX_PER_RUN',
  'CONNECT_DELAY_MS', 'CONNECT_DELAY_MIN_MS', 'CONNECT_DELAY_MAX_MS',
  'CONNECT_SEND_ENABLED',
  'CONNECT_SEND_NOTE', 'CONNECT_NOTE_FALLBACK',
  'DAILY_MESSAGE_LIMIT', 'DAILY_CONNECT_LIMIT',
];

function writeEnvFromDb() {
  const allRows = queryAll('SELECT key, value FROM settings');
  const envMap = Object.fromEntries((allRows || []).map((r) => [r.key, r.value]));
  const envLines = ['# Auto-generated by LinkedIn Dashboard', ''];
  for (const key of ENV_KEYS) {
    if (envMap[key] !== undefined) envLines.push(`${key}=${envMap[key]}`);
  }
  fs.writeFileSync(ENV_FILE, envLines.join('\n') + '\n', 'utf-8');
}

module.exports = { writeEnvFromDb, ENV_KEYS };
